# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eafad663dc7838f4020c7bdfaef0aa4b2e5bcfd4a00644889b3cd243c593cd8e758dade40c51e38c7ca13e1624336454552b346d0e902a4c21fd1ceff3a7265

test:
  secret_key_base: 20105657b801135e2ebe511b75bcef45e4ee0f4a6c386a992c88c76e72cc0b47a3898ac70f4c0dad2caa329c2e8e611640d395f46666598fc72cb93ba9c172c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
